[build]
  functions = "functions"

[[redirects]]
from = "/dealer-integration/"
to = "/.netlify/functions/functions/?subscriberID=:subscriberID&siteID=:siteID"  
query = {subscriberID = ":subscriberID",siteID= ":siteID"}
status = 200