[build]
  functions = "functions"

[[redirects]]
  from = "/dealer-integration"
  to = "/.netlify/functions/functions"
  status = 301
  force = true
  query = {subscriberID = ":subscriberID",siteID= ":siteID"}
